#!/usr/bin/env bash
set -euo pipefail

# Select a configuration using validation predictions already generated by the
# electricity pipelines.  This does not rerun Chronos or LightGBM.
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

SPLIT="${1:-valid}"
OUT="${AUTO_SELECTOR_OUT:-results/auto_selector}"

if [[ "$SPLIT" == "test" ]]; then
  EXTRA=(--allow-test-diagnostic)
else
  EXTRA=()
fi

python scripts/auto_select_mechanism.py \
  --results-root "${RESULTS_ROOT:-results/electricity}" \
  --output-dir "$OUT" \
  --split "$SPLIT" \
  --data "guangdong=data/GD/guangdong_aligned.csv:ds:y" \
  --data "shanxi=data/SHANXI/shanxi_aligned.csv:ds:y" \
  --data "reale_delu=data/REALE/DE-LU_aligned.csv:time:y_Day-ahead Price [EUR/MWh]" \
  --data "reale_fr=data/REALE/FR_aligned.csv:time:y_Day-ahead Price [EUR/MWh]" \
  "${EXTRA[@]}"

echo "Selector output: $OUT"
